config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'bbq#index'
  get 'about', to: 'bbq#about'
  get 'menu', to: 'bbq#menu'
  get 'contact', to: 'bbq#contact'
  resources :rfqs, only: [:new, :create, :update, :show]
  get "thankyou", to: 'rfqs#thankyou'
  resources :foods, only: [:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :rfq

  self.inheritance_column = :types
  def self.types
      %w(Meat Side)
  end

end

app/models/meat.rb
class Meat < Food
    
end

app/models/rfq.rb
class Rfq < ApplicationRecord

  validates_format_of :name, :with => /\A(?=.* )[^0-9`!@#\\\$%\^&*\;+_=]{4,}\z/, :on => :create
  validates_format_of :email, :with => /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, :on => :create
  validates_format_of :phone_number, :with => /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, :on => :create

  has_many :foods
  after_create :meat_selection
  after_create :side_selection
  after_update :send_rfq
  after_update :send_confirmation
  after_update :destroy_rfq
  
  validates_format_of :name, :with => /\A(?=.* )[^0-9`!@#\\\$%\^&*\;+_=]{4,}\z/, :on => :create
  validates_format_of :email, :with => /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, :on => :create
  validates_format_of :phone_number, :with => /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, :on => :create
  validates_presence_of :people_attending
  validates :catering_type, inclusion: { in: [true, false] }

  
  def meat_selection
    Food.create(type: "meat", name: "Pulled Pork", rfq_id: id)
    Food.create(type: "meat", name: "Pork Loin", rfq_id: id)
    Food.create(type: "meat", name: "Tri-Tip", rfq_id: id)
    Food.create(type: "meat", name: "Brisket", rfq_id: id)
    Food.create(type: "meat", name: "Pulled Beef", rfq_id: id)
    Food.create(type: "meat", name: "Ribs (St. Louis)", rfq_id: id)
    Food.create(type: "meat", name: "Ribs (Baby Back)", rfq_id: id)
    Food.create(type: "meat", name: "Chicken Thighs", rfq_id: id)
    Food.create(type: "meat", name: "German Sausages and Hot Links", rfq_id: id)
    Food.create(type: "meat", name: "Seasonal Vegetarian Option", rfq_id: id)
  end

  def side_selection
    Food.create(type: "side", name: "Coleslaw", rfq_id: id)
    Food.create(type: "side", name: "BBQ Beans", rfq_id: id)
    Food.create(type: "side", name: "Potato Salad", rfq_id: id)
    Food.create(type: "side", name: "Macaroni Salad", rfq_id: id)
    Food.create(type: "side", name: "Green Salad", rfq_id: id)
    Food.create(type: "side", name: "Caeser Salad", rfq_id: id)
    Food.create(type: "side", name: "Smoked Bacon Mac and Cheese", rfq_id: id)
    Food.create(type: "side", name: "Fruit Platter", rfq_id: id)
  end

  def foods_ordered(food_ids) 
    food_ids.keep_if{ |v| v != "" }  
    return food_ids.map{|e| Food.find(e).name } 
  end

   CATERING_TYPE = {
    'Catering Service': true,
    'Drop-Off': false
  }

  def pricing
  # 1 Meat, 2 sides $13-$15
  # 2 Meats, 2 sides $15-$18
  # 3 Meats, 2 sides $18-$21
  # Additional sides $2 per person 

  # 1 Meat  $10-$12
  # 2 Meats $12-$15
  # 3 Meats $15-$18 
  end

  def catering_type_humanized
    CATERING_TYPE.invert[self.catering_type]
  end

  def send_rfq
    NotificationMailer.rfq_submitted(self).deliver
  end

  def send_confirmation
    NotificationMailer.rfq_thankyou(self).deliver
  end

  def send_request_email
    NotificationMailer.rfq_added(self).deliver
  end

  def destroy_rfq
    self.destroy 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bbq_controller.rb
class BbqController < ApplicationController

  def index

  end

  def about

  end

  def menu

  end

  def contact

  end

  def meat_params
    
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def update
    #ajax is used here...
    current_choice = Food.find(params[:id])
    current_choice.update(food_params)
  end

  private

  def food_params
    params.require(:food).permit(:selected)
  end

end

app/controllers/rfqs_controller.rb
class RfqsController < ApplicationController

  def new
    @rfq = Rfq.new 
  end

  def create
    @rfq = Rfq.create(rfq_params)
    if @rfq.valid?
      redirect_to rfq_path(@rfq)
    else
      render :new, status: :unprocessable_entity
    end
   
  end

  def update
    @rfq = Rfq.find(params[:id])            
    @rfq.update_attributes(rfq_params)
    if @rfq.valid?
      redirect_to thankyou_path
    else
      render :update, status: :unprocessable_entity
    end
  end

  def show
    @rfq = Rfq.where(id: params[:id]).last
    foods = Food.where(rfq_id: @rfq)
    @meats= foods.where(type: "meat")
    @sides=foods.where(type: "side")
  end

  def thankyou
  end


  private

  def rfq_params
    params.require(:rfq).permit(:name, :email, :phone_number, :event_date, :event_type, :people_attending, :catering_type, :comments, meats: [], sides: [])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bbq_helper.rb
module BbqHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/rfqs_helper.rb
module RfqsHelper
end

app/views/bbq/about.html.erb
<br/>
<div class="fullheight">
  <div class="frosty col-10 offset-1">
    <div class="about">
      <h1><%= title 'About' %></h1>
      <br/>
        <h2>Meet the men that make the meat.</h2>
      <br/>

      <div class="container">
        <div class="row">
          <div class="col">
            <%= image_tag 'doug.jpg', class: "img-fluid about_img" %>
          </div>
           <div class="col">
            <%= image_tag 'jason.jpg', class: "img-fluid about_img" %>
          </div>
        </div>
        
        <div class="row">
          <div class="col text-center">
          <br/>
            <h3>Doug - Owner</h3>
          </div>
          <div class="col text-center">
          <br/>
            <h3>Jason - Owner</h3>
          </div>
        </div>
        <br/>
        <br/>
        <div class="row">
          <div class="col-sm-10 offset-sm-1 text-center">
            <h4><%= description 'Off the Bone BBQ has been providing quality-smoked meats and sides in the Rogue Valley since 2012. We provide full-catering for any event or occassion. We also provide a drop-off service if your event is in a more casual setting.'%></h4>
            <br/>
            <h4>Off the Bone BBQ has whatever mouth-watering meats or sides you crave. Check out our <%=link_to "menu", menu_path, class: "about_link" %> and <%=link_to "request a quote", new_rfq_path, class: "about_link"%> today!</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bbq/contact.html.erb
<br />
<div class= "frosty col-10 offset-1 text-center">
  <h1><%= title 'Contact' %></h1>
  <br />
  <div>
    <%= link_to "mailto:offthebonebbq1@gmail.com", class: "btn btn-success" do %>
      Email Us
     <% end %>
  </div>
  <br/>
  <p>or</p>
  <div>
    <%= link_to "Request a Quote", new_rfq_path, class: "btn btn-primary" %>
  </div>
  <br/>
</div>

app/views/bbq/index.html.erb
<br/>
<div class="fullheight">
  <div class="frosty col-10 offset-1 text-center">
      <h1><%= title 'Off the Bone BBQ Catering'%></h1>
      <br/> 
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active">
            <%= image_tag "bbq1.jpg",  class: 'img-fluid'%>
            <div class="carousel-caption d-none d-md-block">
              <p></p>
            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag 'bbq2.jpg', class: 'img-fluid' %>
            <div class="carousel-caption d-none d-md-block">
              <p></p>
            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag 'bbq3.jpg', class: 'img-fluid' %>
            <div class="carousel-caption d-none d-md-block">
              <p></p>
            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag 'bbq4.jpg', class: 'img-fluid' %>
            <div class="carousel-caption d-none d-md-block">
              <p></p>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div> 
      </div> 

      <div class="index text-center">
        <h2>Our mission is to provide the highest quality, wood-smoked cuisine for any event!</h2>
      </div>
  </div>
</div>


  

app/views/bbq/menu.html.erb
<br/>
<div class="fullheight">
  <div class="frosty text-center col-10 offset-1">
    <div class="container">
      <h1><%= title 'Menu'%></h1>
      <br/>
      <div class="row">
        <div id=meatlist class="col-12 col-sm-6">
          <h3><u>Smoked Meat</u></h3>
          <ul class="food_list">
            <br />
            <li> Pulled Pork</li>
            <li> Pork Loin</li>
            <li> Tri - Tip</li>
            <li> Brisket</li>
            <li> Pulled Beef</li>
            <li> Ribs (St. Louis or Baby Back)</li>
            <li> Chicken Thighs</li>
            <li> German Sausages and Hot Links</li>
            <li> Seasonal Vegetarian Option</li>
         </ul>
        </div>
        <div class="col-12 col-sm-6">
          <h3><u>Side Dishes</u></h3>
          <ul class="food_list">
            <br />
            <li> Coleslaw</li>
            <li> BBQ Beans</li>
            <li> Potato Salad</li>
            <li> Macaroni Salad</li>
            <li> Green Salad</li>
            <li> Caesar Salad</li>
            <li> Smoked Bacon Macaroni and Cheese</li>
            <li> Fruit Platter</li>
          </ul>
        </div>
      </div>
    </div>
    <br/>
    <%= link_to "Request a Quote", new_rfq_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <%= display_meta_tags site: 'Off the Bone BBQ Catering'%>
    <% set_meta_tags description: 'Off the Bone BBQ offers delicious wood-smoked cuisine for any occassion.', 
                      keywords: 'Off the Bone,BBQ,catering,barbeque,smoked,food,restaurant,Medford,OR,Southern,Oregon'%>
    <meta name = "description" content = "Off the Bone Catering offers delicious wood-smoked cuisine for any occassion" keywords = "Off the Bone,BBQ,catering,barbeque,smoked,food,restaurant,Medford,OR,Southern,Oregon"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Alice');
    </style>
  </head>

  <body>
    <div id="flex-container">
      <nav class="navbar">
        <div class="container-fluid">
          <div class="row h_links">
            <div class="col-md">
              <%= link_to 'HOME', root_path %>
            </div>
            <div class="col-md">   
              <%= link_to 'ABOUT', about_path %>
            </div>
            <div class="col-md">
              <%= link_to 'MENU', menu_path %>
            </div>
            <div class="col-md"> 
              <%= link_to 'CONTACT', contact_path %>
            </div>
          </div>
        </div>
      </nav>
      <div class="main">
        <%= yield %>
      </div>
      <div id="footer">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md text-center f_title">
              <u>CONTACT</u>
              <div class="f_link"> 
                <%= link_to "mailto:offthebonebbq1@gmail.com" do %> 
                  <i class="fa fa-envelope"></i>&nbsp;&nbsp;Email Us
                <% end %>
              </div>
              <div class="f_link">
                <%= link_to "tel:+1-541-690-8689" do%>
                  <i class="fa fa-phone"></i>
                    &nbsp;541-690-8689
                <% end %>
              </div>
            </div>
            <br/>
            <div class="col-md text-center f_title">
              <u>REQUEST A QUOTE</u>
              <div class="f_link">
                <%= link_to new_rfq_path do %>
                  <i class="fa fa-telegram"></i>&nbsp;&nbsp;Request a Quote
                <% end %>
                <div class="f_link"> 
                <%= link_to "mailto:gretchen.zigzag@gmail.com" do %> 
                  <i class="fa fa-envelope"></i>&nbsp;&nbsp;Website: Gretchen Ghrist
                <% end %>
              </div>
              </div>
            </div>
            <br/>
            <div class="col-md text-center f_title">
              <u>SOCIAL</u>
              <div class="f_link">
                <%= link_to "https://facebook.com/OffTheBoneBbqGrill", target: :_blank do%>
                  <i class="fa fa-facebook"></i>
                  &nbsp;Facebook
                <% end %>
              </div>
              <div class="f_link">
                <%= link_to "https://yelp.com/biz/off-the-bone-bbq-central-point", target: :_blank do%>
                <i class="fa fa-yelp"></i>
                  &nbsp;Yelp
              <% end %>
              </div>
            </div>
            <br />
          </div>
          <div class="row">
            <div class="col-md text-center">
              <i class="fa fa-copyright"></i> Copyright 2017 to 2023 | All Rights Reserved
            </div>
          </div>
        </div>
      </div>
    </div> 
  </body>
</html>

app/views/rfqs/new.html.erb
<br/>
<br/>
<div class="fullheight">
  <div class="frosty col-10 offset-1">
    <div class="col-10 offset-1">
      <br/>
      <br/>
      <h2>Please Enter Your <%=title 'Contact Information'%></h2>
      <%= simple_form_for @rfq do |f| %>
        <br/>
        <div class="row">
          <div class="col-sm-6">
            <%= f.input :name, placeholder: "John Smith" %>
          
            <%= f.input :email, placeholder: "smith@email.com"%>
            <%= f.input :phone_number, placeholder: "541-123-1234"%>
            <%= f.input :company_name, placeholder: "Business Name" %>
         
            
          </div>
          <div class="col-sm-6">
            <%= f.input :catering_type, as: :select, collection: Rfq::CATERING_TYPE %>
            <%= f.input :event_type, placeholder: "Wedding"%>
            <%= f.input :people_attending, as: :select, collection: 25..400, step: 5 %>
            <%= f.input :event_date, as: :date, start_year: Date.today.year,
                                end_year: Date.today.year + 3,
                                order: [:month, :day, :year]%>
          </div>
        </div>
        <br/>
        <div class="text-center">
          <%= f.submit 'Next to Menu Selection', class: 'btn btn-primary' %>  
        </div>
      <% end %>
      <br/>
    </div>
  </div>
</div>

app/views/rfqs/show.html.erb
<script>          
  $(function() {
    var s = $('.food');
    touchStart = function (event) {
        event.preventDefault();
        $(this).addClass("touched");
    };
     touchEnd = function (event) {
        event.preventDefault();
        $(this).removeClass("touched");
    };
    s.ontouchstart = touchStart;
    s.ontouchend = touchEnd;
    $(s).bind("touchstart mousedown", function (e){
      console.log(e.type);
    });
    $(s).bind("touchend mouseup", function (e) {console.log(e.type);
    });
    $('.food').change(function(e) {
      var foodId = $(e.target).data("value");
      if (this.checked == true) {
        var selectedFood = Boolean($(e.target).is(':checked')); 
        // console.log(selectedFood);
        $.ajax({
          type: 'PUT',
          url: "/foods/" + foodId,
          data: { food: {selected: selectedFood} },
        });
      } else {
        var deSelectedFood = Boolean($(e.target).is(''));
        // console.log(deSelectedFood);
         $.ajax({
          type: 'PUT',
          url: "/foods/" + foodId,
          data: { food: {selected: deSelectedFood} },
        });
      };
    });
  });
</script>
<br/>
<br/>
<div class="fullheight">
  <div class="frosty">
    <div class="container">
      <div class="col-10 offset-1">
        <br/>
        <br/>
        <div class="text-center">
          <h1><%=title 'Choose From Our Menu'%></h1>
        </div>
      
      <div class="row">
        <div class="col-12 col-sm-6">
          <br/>
          <h3 class="text-center"><u>Smoked Meat</u></h3>
          <div class="col-12">
            <ul id="meatlist">
            <br />
              <%= simple_form_for @rfq do |f| %>
                <%=f.collection_check_boxes(:meats, @meats.all, :id, :name, checked: @meats.where(selected: true).map(&:id), unchecked: @meats.where(selected: false).map(&:id) ) do |b| %>
                  <li>
                    <%=b.check_box("data-value": b.value, "data-text": b.text, class: "food") %>
                    <%=b.label(class: "meat_name")%>
                <%end%>
                  </li>
            </ul>
          </div>
        </div>
        <div class="col-12 col-sm-6">
          <br/>
          <h3 class="text-center"><u>Side Dishes</u></h3>
          <div class="col-12">
            <ul id="sidelist">
            <br />
                <%=f.collection_check_boxes(:sides, @sides.all, :id, :name, checked: @sides.where(selected: true).map(&:id), unchecked: @sides.where(selected: false).map(&:id) ) do |b| %>
                  <li>
                    <%=b.check_box("data-value": b.value, "data-text": b.text, class: "food") %>
                    <%=b.label(class: "side_name")%>
                <%end%>
                  </li>
            </ul>
          </div>
        </div>
        <div class="col-12 col-sm-10 offset-sm-1">
                <%= f.input :comments %>
        </div>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <div class="col-12 text-center">
                  <%= f.submit 'Submit for Quote', class: 'btn btn-primary ', method: :put %>
                <% end %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/rfqs/thankyou.html.erb
<br/>
<br/>
<div class="fullheight">
  <div class="frosty col-10 offset-1 text-center">
    <h2><%=title 'Thank you'%> for submitting for a quote from us at Off the Bone BBQ!</h2>
    <h4>We will be contacting you shortly to provide you with a quote.</h4>
  </div>
</div>